### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by TrySound** [chpio/rollup-plugin-css-modules#1]
Hey! Do you plan any improvements on this? I have a project where this feature could be relevant. You can give me an access to let me cover this project with tests and functionality.

**Comment by TrySound** [comment]
@chpio In case you are end with it. Would you like to share npm access too?

**Comment by chpio** [comment]
you could also just add a PR

> Do you plan any improvements on this?

yeah, what should be added to the todo list (beside a release)?
